# action.yml
name: "Branch Flow Detector"
description: "Detects code changes in a Pull Request and validates the branch flow (dev → staging → main)."
author: "Ricardo Malnati"

branding:
  icon: "git-branch"
  color: "purple"

inputs:
  token:
    description: "GitHub token (ex.: secrets.GITHUB_TOKEN)"
    required: true

outputs:
  allowed:
    description: "Indica se o fluxo de branches é permitido"
    value: ${{ steps.validate_flow.outputs.allowed }}
  head_branch:
    description: "Nome da branch de origem"
    value: ${{ github.event.pull_request.head.ref }}
  base_branch:
    description: "Nome da branch de destino"
    value: ${{ github.event.pull_request.base.ref }}

runs:
  using: "composite"
  steps:
    # ========================================================================
    # STEP 1: CLASSIFICAR BRANCH DE DESTINO (BASE)
    # Responsabilidade: Identificar se o alvo é Prod, Stage ou Dev
    # ========================================================================
    - id: classify_base
      shell: bash
      env:
        BASE: ${{ github.event.pull_request.base.ref }}
        DEFAULT: ${{ github.event.repository.default_branch }}
      run: |
        set -euo pipefail
        
        TYPE="other"
        
        # Normaliza lista de branches conhecidas
        case "$BASE" in
          "$DEFAULT"|main|master|prd|prod|production|producao)
            TYPE="production"
            ;;
          staging|stage|hm|hom|homol|homolog|homologation|homologacao)
            TYPE="staging"
            ;;
          dev|develop|development)
            TYPE="development"
            ;;
        esac
        
        echo "base_type=$TYPE" >> "$GITHUB_OUTPUT"

    # ========================================================================
    # STEP 2: CLASSIFICAR BRANCH DE ORIGEM (HEAD)
    # Responsabilidade: Identificar se a origem é Stage ou Dev
    # ========================================================================
    - id: classify_head
      shell: bash
      env:
        HEAD: ${{ github.event.pull_request.head.ref }}
      run: |
        set -euo pipefail
        
        TYPE="other"
        
        case "$HEAD" in
          staging|stage|hm|hom|homol|homolog|homologation|homologacao)
            TYPE="staging"
            ;;
          dev|develop|development)
            TYPE="development"
            ;;
        esac
        
        echo "head_type=$TYPE" >> "$GITHUB_OUTPUT"

    # ========================================================================
    # STEP 3: VALIDAR FLUXO (REGRA DE NEGÓCIO)
    # Responsabilidade: Cruzar Base vs Head e definir 'Allowed'
    # ========================================================================
    - id: validate_flow
      shell: bash
      env:
        BASE_TYPE: ${{ steps.classify_base.outputs.base_type }}
        HEAD_TYPE: ${{ steps.classify_head.outputs.head_type }}
      run: |
        set -euo pipefail
        
        ALLOWED="true"
        REASON="Fluxo padrão"

        if [ "$BASE_TYPE" == "production" ]; then
          # Para ir para Prod, a origem DEVE ser Staging
          if [ "$HEAD_TYPE" != "staging" ]; then
            ALLOWED="false"
            REASON="Envio para Produção permitido apenas via Staging."
          fi
        elif [ "$BASE_TYPE" == "staging" ]; then
          # Para ir para Staging, a origem DEVE ser Development
          if [ "$HEAD_TYPE" != "development" ]; then
            ALLOWED="false"
            REASON="Envio para Staging permitido apenas via Development."
          fi
        fi

        echo "allowed=$ALLOWED" >> "$GITHUB_OUTPUT"
        echo "reason=$REASON" >> "$GITHUB_OUTPUT"

    # ========================================================================
    # STEP 4: CONSTRUIR MENSAGEM
    # Responsabilidade: Montar texto do comentário baseado nos resultados anteriores
    # ========================================================================
    - id: build_message
      shell: bash
      env:
        ACTOR: ${{ github.actor }}
        ALLOWED: ${{ steps.validate_flow.outputs.allowed }}
        REASON: ${{ steps.validate_flow.outputs.reason }}
        HEAD: ${{ github.event.pull_request.head.ref }}
        BASE: ${{ github.event.pull_request.base.ref }}
        DEFAULT: ${{ github.event.repository.default_branch }}
      run: |
        set -euo pipefail

        HEADER_TITLE="🔀 flow-check"
        HEADER_SUBJECT="Fluxo de branches e alterações de código"
        
        BODY_MSG=""
        RESULT=""
        ADVISE=""
        
        # Constrói o bloco de escopo (Metadata)
        SCOPE_BLOCK="- head: \`$HEAD\`
        - base: \`$BASE\`
        - default: \`$DEFAULT\`
        - has_code: \`$HAS_CODE\`
        - allowed: \`$ALLOWED\`"

        if [ "$HAS_CODE" == "false" ]; then
          # Caso 1: Sem código (apenas docs, imagens, etc)
          BODY_MSG="🟡 Nenhuma alteração de código fonte detectada."
          RESULT="Nenhuma alteração de código."
          ADVISE="O fluxo de branches não será bloqueado, mas outras validações podem se aplicar."
        
        elif [ "$ALLOWED" == "true" ]; then
          # Caso 2: Tem código e Fluxo Correto
          BODY_MSG="✅ Fluxo de branches **permitido** e alterações de código detectadas."
          RESULT="Fluxo permitido."
          ADVISE="Continue com as validações e revisões habituais."
        
        else
          # Caso 3: Tem código e Fluxo Incorreto
          BODY_MSG="⛔ Fluxo de branches **não permitido** para esta Pull Request."
          SCOPE_BLOCK="$SCOPE_BLOCK
        - reason: $REASON
        - rule: dev → staging → main"
          RESULT="Fluxo inválido."
          ADVISE="Ajuste a origem/destino para respeitar o fluxo dev → staging → main."
        fi

        {
          echo "header_actor=$ACTOR"
          echo "header_title=$HEADER_TITLE"
          echo "header_subject=$HEADER_SUBJECT"
          echo "footer_result=$RESULT"
          echo "footer_advise=$ADVISE"
          
          # Multiline outputs
          echo "body_message<<EOF"
          echo "$BODY_MSG"
          echo "EOF"
          
          echo "body_scope<<EOF"
          echo "$SCOPE_BLOCK"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    # ========================================================================
    # STEP 5: POSTAR COMENTÁRIO
    # ========================================================================
    - id: post_comment
      uses: Malnati/pr-comment@v4.0.5
      with:
        token: ${{ inputs.token }}
        pr_number: ${{ github.event.pull_request.number }}
        header_actor: ${{ steps.build_message.outputs.header_actor }}
        header_title: ${{ steps.build_message.outputs.header_title }}
        header_subject: ${{ steps.build_message.outputs.header_subject }}
        body_message: ${{ steps.build_message.outputs.body_message }}
        body_scope: ${{ steps.build_message.outputs.body_scope }}
        body_todo: "" # Não utilizado nesta action
        footer_result: ${{ steps.build_message.outputs.footer_result }}
        footer_advise: ${{ steps.build_message.outputs.footer_advise }}
        template_path: "message.md"
